### ISSUE TITLE
[Q] Does this get overwritten on Synology updates?

### ISSUE THREAD

**Issue by pkkid** [insistent-afk/cloudflare-ddns-for-synology#4]
I'd like to add my own custom DDNS provider for Digital Ocean. They require a PUT request to their API endpoint. So a basic Custom Provider via the UI will not work. I like the idea of integrating it like this as I a custom script on synology to do the update.

Anyway, this seems a bit intrusive to the Synology OS and I am curious if this patch to their code gets overwritten with Synology updates?

**Comment by insistent-afk** [comment]
If Synology has a version update, it is necessary to reinstall this script.

**Comment by pkkid** [comment]
Thank you for the answer.
